---
name: Setup Node
description: Setup Node.js and install dependencies.

inputs:
  node_version:
    description: The Node.js version.
    required: false
    default: '16'

runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true
    - name: Setup cache
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        cache: npm
        node-version: ${{ inputs.node_version }}
    - name: Install dependencies
      shell: bash
      run: npm ci
